import React from 'react'

const Nota = () => {
    return (
        <div id= "nota-content">
            <div id= "img-logo-wrapper">
            <img id= "imagen-principal"src=  "https://www.atlanticcouncil.org/wp-content/uploads/2020/04/HMS-QEII-large-1024x683.jpg"></img>
            <div id= "redes">
                <button className="redes-button"> <i class="fas fa-mail-bulk"></i> </button>
                <button className="redes-button"> <i class="fab fa-facebook-f"></i> </button>
                <button className="redes-button"> <i class="fab fa-twitter"></i> </button>
                <button className="redes-button"> <i class="fab fa-linkedin"></i> </button>
            </div>
            </div>
            <p id="epigrafe">People watch on as the Royal Navy aircraft carrier HMS Queen Elizabeth sails into the Solent after leaving Portsmouth harbour to undergo further sea trials. (Reuters)</p> 
            <p className="texto">Long before the coronavirus pandemic began battering European economies, NATO’s European allies had already found it difficult to find the cash or the political will to invest the two percent of gross domestic product on defense they agreed to in 2014. In the wake of the economic calamity caused by the coronavirus, the situation will become dire, and will have knock on implications for transatlantic security. Yet NATO’s security threats will not go away.
            This does not mean, however, that Europe cooperation on defense issues should take two steps back—now is the perfect time for European militaries to work together to maximize their resources and military readiness. No better opportunity exists than to use HMS Queen Elizabeth and HMS Prince of Wales as hubs for a European carrier strike group.</p>
            <h1 className="texto-title">Return of the carriers</h1>
            <p className="texto"> For the better part of two centuries the Royal Navy (RN) was the worlds’ most potent fighting force. At its peak, the British navy had some 332 warships. Today it is a shadow of its former self, with the Ministry of Defense projecting approximately thirty ships fit for service in 2020. But for the first time since the decommissioning of the HMS Ark Royal in 2011, the navy once again has an aircraft carrier back in service—the 65,000 ton HMS Queen Elizabeth (R08). Her sister ship the HMS Prince of Wales is now in sea trials.
            The largest carriers ever operated by the RN, these ships are highly automated and extremely advanced. They are capable of deploying up to thirty-six F-35B Lightning II Joint Strike Fighters (JSF). The level of automation on the ships means that the core crew of the carriers is only 800 sailors and officers. With an air wing onboard this number doubles. One immediate challenge for the Royal Navy is that the UK buy rate for the F-35B is such that it will take until 2024 to get to just twenty-four British F-35Bs on the decks of the carriers. Furthermore, it will not be possible for the UK to operate both vessels simultaneously, but the idea is that one carrier will be deployed at a time with the other waiting in the wings. When the HMS Queen Elizabeth cycles out for scheduled service, the crew will transfer to the HMS Prince of Wales, thereby allowing the UK to have continuous carrier capability. This also helps the RN overcome staffing shortages—the Royal Navy isn’t large enough to fill the billets for two carriers, never mind two full carrier groups, simultaneously.
            It has long been rumored amongst defense analysts that the plan for the UK carriers is for them to serve as part of a combined US-UK carrier strike group. Such plans would build on a long cooperative relationship stretching back a century. In particular, cooperation between the Royal Navy and US Navy (USN) on naval nuclear issues is a critical feature of the “special relationship” and demonstrates the close linkages between the two forces. Future cooperation was officially outlined in December 2014 when the USN and RN released the report of an Anglo-American study group titled “Combined Seapower: A Shared Vision for Royal Navy-US Navy Cooperation” that highlighted shared strategic goals and outlined future avenues of cooperation. Not surprisingly, right after sea trials in 2018 the HMS Queen Elizabeth promptly steamed westward to the United States. She did the same again in 2019 to partake in exercises with the US military off the eastern seaboard with the explicit goal of improving not simply the interoperability of US-UK forces, but to advance true integration. When the HMS Queen Elizabeth goes on her first deployment in 2021 to Asia, her twelve British F-35Bs will be joined by a squadron of US Marine Corps F-035B jets flow by US pilots so the carrier has a more robust complement of combat aircraft. But the Royal Navy has more to worry about than just a lack of combat aircraft—it also doesn’t really have to ships to complement a full-scale carrier strike group on near continuous deployment.
            In 2019, the Westlant 19 deployment of the Royal Navy carrier strike group consisted of the HMS Queen Elizabeth, flanked by the air defense destroyer HMS Dragon, the anti-submarine frigate HMS Northumberland, and the fleet tanker FRA Tideforce. For her 2021 deployment, the Royal Navy expects to deploy the Queen Elizabeth with additional escorts—two type 45 destroyers, two Type 23 frigates, a nuclear submarine, plus a tanker and fleet supply ship. The problem for the Royal Navy is that over the long term the Royal Navy cannot continue to deploy such a strike group without negatively impacting other commitments—there are not enough warships in the Royal Navy to support repeat deployments. The RN only has six destroyers, thirteen frigates, and six fast attack submarines. When one factors in rotations for refit and repair, the number of deployable vessels at any one time is about 66 percent of the total available—give or take twelve vessels available at any one time. The answer to filling this need is to not just to advance interoperability with the US Navy and Marine Corps, but to include European allies as well.</p>
            <h1 className="texto-title">Britannia and Europa, hand in hand</h1>
            <p className="texto"> It is entirely understandable that the first mission for Britain’s first ever carrier strike group be a wholly sovereign endeavor, but going forward pride should take a back seat to capability and effectiveness in NATO. Indeed it must, since the Royal Navy does not have enough billets, ships, or fighter aircraft to continually operate a carrier strike group. Naval cooperation between the United States and UK is a step in the right direction, not just because the RN faces budget constraints, but also because the US Navy’s own plan for 435 ships is a pipe dream, especially in the wake of COVID-19. Cooperation with Europe is also necessary and it is here that the UK can resume its highly valuable role as a bridge between the continent and the United States. Using the British carriers as the center of a British-led, but European-supported, task force would add a serious pillar of capability to NATO. Such a move should be compatible with the Government’s strategic goals in the coming decade as outlined by Prime Minister Boris Johnson.
            As Brexit negotiations began, then Foreign Secretary Boris Johnson argued that although Britain was leaving the European Union, it was not leaving Europe. Brexit was not, according to Johnson, “any kind of mandate for the country to turn in on itself, to haul up the drawbridge, to detach itself from the international community.” The UK has also stated repeatedly, over many decades, that NATO is the preferred forum for European security and defense issues. Establishing a carrier strike group that is truly European would be a major leap forward for the Alliance. It would allow the United States to reposition forces and would give Britain and her European NATO allies truly global reach.
            Creating a UK-led NATO-Europe Strike Group would be functionally relatively easy and builds on training exercises such as Brilliant Mariner, Poseidon, Joint Warrior, Dynamic Mongoose, and Formidable Shield. Furthermore, the British and the French have been ramping up military cooperation since signing the 2010 Lancaster Treaties. The naval side of Combined Joint Expeditionary Force is a model for cooperation. 
            Collectively, the navies of Europe possess an immense amount of resources. When participating in NATO exercises, it is hard to ignore the robustness of European naval capabilities. The challenge is, however, overcoming the friction between national and multinational commitments—a problem that will only worsen in an era of constrained national budgets following the coronavirus pandemic. It would behoove all involved to accept the reality that working together is the best way forward. Furthermore, no European navy is going to launch a unilateral naval campaign, and really, most likely, no European naval campaign would be launched without the blessing (and most likely support, at least in terms of Command, Control, Communications, Computers, Intelligence, Surveillance, and Reconnaissance—C4ISR) from the United States. Forming a European carrier strike group deployed globally, therefore, is a major way to advance collective action within NATO, demonstrate solidarity on defense capabilities to Washington, and to utilize resources most effectively. Such solidarity is necessary in a world where China will outstrip the US Navy in coming decades. Europe allies cannot simple depend on the United States—they must contribute actively to global security.</p>


            <div id= "report">
                <div id="report-text">
                <h1>Moving Out: A Comprehensive Assessment of European Military Mobility</h1>
                <p id="report-p" >Military mobility is the logical and critical next step to enhancing the 21st century conventional deterrence posture throughout Europe, an essential part of the formula for keeping the peace.</p>
                <button className="btn"> READ THE REPORT </button>
                </div>
                <img id="report-pic" src="https://www.atlanticcouncil.org/wp-content/uploads/2020/04/Bradley-IFV-Germany-Crop.jpg"></img>
            </div>

            <p className="texto"> The navies of Europe have some excellent force options to support the HMS Queen Elizabeth with air, surface, and subsurface defense. The Danish Iver Huitfeld-class frigate Peter Willemoes passed the British Flag Officer Sea Training test in 2015 and the Huitfeld class is the basis for the forthcoming  “Arrowhead 140” Type 31 frigate the British will begin building shortly. The Dutch De Zeven Provincien-class frigates, like De Ruyter or Evertsen, are also up to the task with a highly advanced weapons and sensor suite. Optimized for air defense, these ships can also serve in an anti-submarine and anti-surface combatant capacity. The Norwegian Fridtjof Nansen-class frigates can also serve in the same role, as too can the French La Fayette-class frigates and the Alvaro de Bazan-class frigates of the Spanish navy. The Italian and French Horizon class destroyer, designed with the intent of carrier escort, is another, lighter escort option. Germany is, for a number of reasons, perhaps a more difficult partner, but the F124 Sachsen class frigate, which is more on par with a UK or US destroyer, could also handily fill the role of destroyer escort. And of course, just because it is a predominately European carrier group doesn’t mean that, in addition to US Marine Corps F35 jets, the strike group cannot incorporate US vessels such as a Virginia-Class fast attack submarines for subsurface escort.</p>
            <h1 className="texto-title">Europe proves its worth</h1>
            <p className="texto">The most critical element in the formation of a UK-led NATO Europe Carrier Strike Group will be political will. The capabilities exist across European NATO allies to continuously deploy such a group; it will come down to cooperation amongst NATO allies to make it a reality. For many years, interoperability in Europe has occurred in smaller regional groupings. The UK, in particular, has focused on close cooperation with the Danes, the Baltics, and on some issues with the Dutch. It would be logical that the first deployment of a UK-led NATO Europe Carrier group would involve these partners and then expand with subsequent deployments.
            The reality of NATO in the 21st century is that the United States will not be able to match emergent peer competitors alone. Strong European capabilities are necessary both to ensure stability, but also to stave off isolationist tendencies in the Washington where a sentiment reigns that the United States carries too much of the burden of European defense. Importantly, a UK-led NATO Europe carrier strike group would not just be a potent fighting force, but it would also deal a serious blow to those who argue that Europe fails to substantially contribute to NATO capabilities. The UK-led NATO European carrier strike group would serve as an example that could also be applied carrier strike groups built around the French carrier Charles de Gaulle and the Italian carrier Giuseppe Garibaldi. Such integration would be a serious step forward for allied defense integration in NATO.
            Professor Michael John Williams is a nonresident senior fellow in the Scowcroft Center for Strategy and Security’s Transatlantic Security Initiative at the Atlantic Council and director of the Program in International Relations at New York University
            </p>
            <form>
                <h1>Subscribe for events and publications on NATO</h1>
                <p className="texto">Sign up for updates from the Atlantic Council’s Transatlantic Security Initiative, covering the debate on the greatest security challenges facing the North Atlantic Alliance and its key partners.</p>
                <p className= "texto">Name:</p>
                <div id="name-box">
                    <input className= "input"></input>
                    <input className= "input"></input>
                    <p className= "texto">First</p>
                    <p className= "texto">Last</p>
                </div>
                <p className= "texto">Email*</p>
                <input className= "input" id="email-input"></input>
                <br/>
                <button className= "btn">Submit</button>
            </form>
        </div>
    )
}

export default Nota
